# SaberSim Daily Configuration
# Update token as needed (typically hourly)
# Update slate_id once per day

token: "eyJhbGciOiJSUzI1NiIsImtpZCI6IjNmZDA3MmRmYTM4MDU2NzlmMTZmZTQxNzM4YzJhM2FkM2Y5MGIyMTQiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiam9obiBkYXZpZSIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9zYWJlcnNpbXVpIiwiYXVkIjoic2FiZXJzaW11aSIsImF1dGhfdGltZSI6MTczMzUzNDUyOSwidXNlcl9pZCI6InhrUEhFWGFuTnNoTHcyQ1lRT0l5ZllIZTEzRTMiLCJzdWIiOiJ4a1BIRVhhbk5zaEx3MkNZUU9JeWZZSGUxM0UzIiwiaWF0IjoxNzMzNTM0NTI5LCJleHAiOjE3MzM1MzgxMjksImVtYWlsIjoiY2l5b2c2ODQ4MUBiZmxjYWZlLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJjaXlvZzY4NDgxQGJmbGNhZmUuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.h8ghumAWSmXVyx47eRHZAzFetsclaoS7Dtvtd3yHH2h1Z7vvjv6cEpbMshtBPl1lFWVVI1yloFU5cjZ1fuUlbDlJ30lzQY6NVnxpdmMPI3K_gC9JXkAl4grlab6JKyCNvaRiXj2Mc28UlXA2vCeqGp13SAgmsxrVNxUn8H82IF55CTPXWKuJntzkm-IOweLB3E-t1mjEEjMWZbHt73FsKk13WqDRexKy_meSZWfaZQlb5k7vsPwD0UK8Qj2vnRaph15ygFjjGjuO0GBPSfb07HXRJweA61F88zTx6NGbkXO-T6DIg24yb3iqLI_dqrgmQOjBPQZfXjx74KDFCQMyMQ"

slate_id: "e69f068c-f0de-462d-b88b-e6dafc1bb1f1"

# Example format for pasting:
# token: eyJhbGc...etc  (do not include "Bearer" prefix)
# slate_id: 775184d9-1165-454a-9a26-8634df781cd8